name: Loop and Print Array

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  loopAndPrintJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Loop and Print
        run: |
          myArray=("Item 1" "Item 2" "Item 3" "Item 4")

          for item in "${myArray[@]}"; do
            echo "Array item: $item"
          done
        shell: bash
